### ISSUE TITLE
Cost of the BOTA minione Sensor for F/T for 6D F/T Estimation?

### ISSUE THREAD

**Issue by f5ces27er5c767s** [linchangyi1/9DTact#10]
Hi @linchangyi1 I have been looking everywhere for the cost/price of the BOTA minione Sensor used in the paper, did you order it from the main website or from some third party vendor?

We might need it to further retune our model but even contacting them we are getting no reply.

Apologies, we know this might not be the right place to ask but it is worth trying because we want to get your work running for our research application :) Thank you!

**Comment by linchangyi1** [comment]
Hi, I did this project in China and purchased it from a third-party vendor. If you are also based in China, you can email me for the contact information.

**Comment by abtabrizi** [comment]
hi @linchangyi1, looking at the BOTA sensors, did you use the Serial or USB variation of the MiniONE pro? 

![image](https://github.com/user-attachments/assets/883ac909-bf72-4d11-9ba9-4be0e3e629cb)

from your experience, was the sensor easy to setup and work with? did it require any signal conditioners/amplifier boards + power supplies to operate the sensor? I'm asking this because most 6-axis F/T sensors I have seen required additional modules/boards aside from the sensor itself, for example, the ATI 6-axis sensor we have in our lab requires the following setup:

<a href="url"><img src="https://github.com/user-attachments/assets/50547966-30fc-4130-a430-0618615f267e" align="middle" height="350" width="450" ></a>

lastly, should I be able to use the MiniONE non-pro USB version for data collection? assuming that I would have to tweak the codes provided on your repo.

**Comment by linchangyi1** [comment]
I used the USB one. It's easy to set up it, just requiring the force sensor itself.
